In [2]:
import numpy as np

In [5]:
arr = np.random.rand(5,5)
print(arr)

[[0.84231371 0.41435028 0.5828768  0.43642238 0.54546653]
 [0.50586142 0.10403926 0.65801292 0.92989077 0.70861718]
 [0.06331533 0.44156137 0.59243903 0.72095692 0.62227475]
 [0.28879635 0.54234453 0.10333645 0.75340938 0.4188741 ]
 [0.22817204 0.44600673 0.11994295 0.42492636 0.89898174]]


### Element-Wise Addition, Subraction, Multiplication, and Division

In [7]:
print(arr+10, "\n")
print(arr-10, "\n")
print(arr*10, "\n")
print(arr/10, "\n")

[[10.84231371 10.41435028 10.5828768  10.43642238 10.54546653]
 [10.50586142 10.10403926 10.65801292 10.92989077 10.70861718]
 [10.06331533 10.44156137 10.59243903 10.72095692 10.62227475]
 [10.28879635 10.54234453 10.10333645 10.75340938 10.4188741 ]
 [10.22817204 10.44600673 10.11994295 10.42492636 10.89898174]] 

[[-9.15768629 -9.58564972 -9.4171232  -9.56357762 -9.45453347]
 [-9.49413858 -9.89596074 -9.34198708 -9.07010923 -9.29138282]
 [-9.93668467 -9.55843863 -9.40756097 -9.27904308 -9.37772525]
 [-9.71120365 -9.45765547 -9.89666355 -9.24659062 -9.5811259 ]
 [-9.77182796 -9.55399327 -9.88005705 -9.57507364 -9.10101826]] 

[[8.42313713 4.14350282 5.828768   4.36422385 5.45466531]
 [5.05861424 1.0403926  6.58012918 9.29890771 7.08617182]
 [0.63315333 4.41561367 5.92439031 7.20956917 6.22274751]
 [2.88796348 5.42344529 1.0333645  7.53409384 4.18874101]
 [2.28172035 4.46006733 1.1994295  4.24926356 8.98981743]] 

[[0.08423137 0.04143503 0.05828768 0.04364224 0.05454665]
 [0.05058614 

In [9]:
# the above operations can be performed using numpy built-in functions
# this would save memory as the output can be stored in the original array rather than assigning new memory

arr1 = np.array([1,2,3])
np.add(arr1,[5,6,7],out =arr1)
print(arr1)

np.subtract(arr1,[5,6,7],out =arr1)
print(arr1)

np.multiply(arr1,[5,6,7],out =arr1)
print(arr1)





[ 6  8 10]
[1 2 3]
[ 5 12 21]


### Element-Wise Exponentiation 

In [10]:
print(np.exp(arr))

[[2.32173259 1.51338715 1.7911839  1.54716215 1.72541315]
 [1.6584135  1.10964402 1.93095156 2.53423235 2.03118056]
 [1.06536273 1.55513346 1.80839377 2.05640007 1.86316145]
 [1.33481986 1.72003481 1.10886442 2.12423    1.52024895]
 [1.25630143 1.56206198 1.12743253 1.52947778 2.45709988]]


### Element-Wise Logarithm

In [11]:
print(np.log(arr)) # natural log

[[-0.17160275 -0.88104357 -0.53977944 -0.82914473 -0.60611383]
 [-0.68149251 -2.26298695 -0.41853072 -0.07268815 -0.34443984]
 [-2.75962775 -0.81743827 -0.52350731 -0.3271759  -0.47437356]
 [-1.24203352 -0.61185382 -2.26976511 -0.28314653 -0.87018488]
 [-1.47765539 -0.80742123 -2.12073906 -0.85583941 -0.10649255]]


In [12]:
print(np.log2(arr)) # base 2

[[-0.24757044 -1.27107719 -0.77873711 -1.19620299 -0.87443742]
 [-0.98318587 -3.26480005 -0.60381219 -0.10486683 -0.49692165]
 [-3.98130127 -1.17931414 -0.7552614  -0.47201505 -0.68437638]
 [-1.7918756  -0.88271847 -3.27457887 -0.40849409 -1.25541141]
 [-2.13180611 -1.16486261 -3.05957973 -1.23471527 -0.15363628]]


In [14]:
print(np.log10(arr)) # base 10

[[-0.07452613 -0.38263236 -0.23442323 -0.36009298 -0.26323189]
 [-0.29596844 -0.98280275 -0.18176558 -0.03156806 -0.14958832]
 [-1.1984911  -0.35500893 -0.22735634 -0.14209069 -0.20601782]
 [-0.5394083  -0.26572474 -0.98574646 -0.12296897 -0.37791649]
 [-0.64173758 -0.35065859 -0.92102527 -0.37168633 -0.04624913]]


### Element-Wise Square Root

In [15]:
print(np.sqrt(arr))

[[0.91777651 0.64370046 0.76346369 0.66062272 0.73855706]
 [0.71123936 0.32255117 0.81117995 0.96430844 0.84179403]
 [0.25162538 0.66450084 0.76970061 0.84909182 0.78884393]
 [0.53739776 0.73644045 0.32145987 0.86799158 0.64720484]
 [0.47767357 0.66783735 0.34632781 0.65186376 0.94814648]]


### Element-Wise Sine and Cosine

In [16]:
print(np.sin(arr), "\n")
print(np.cos(arr))

[[0.74618544 0.40259528 0.550428   0.42269989 0.51881698]
 [0.48456116 0.10385167 0.61154586 0.80155464 0.65078447]
 [0.06327304 0.42735159 0.55838606 0.66010379 0.58288503]
 [0.28479863 0.5161455  0.10315264 0.6841294  0.40673215]
 [0.22619732 0.43136635 0.11965557 0.41225369 0.78269355]] 

[[0.66573815 0.91537809 0.83488264 0.90626972 0.85488534]
 [0.87475739 0.9945928  0.79120898 0.59792154 0.75926252]
 [0.99799625 0.90408551 0.82958123 0.75117441 0.81255464]
 [0.95858737 0.85650092 0.99466554 0.72936065 0.91354746]
 [0.9740815  0.90217685 0.99281546 0.9110691  0.62240727]]


### Sume Along A specified Axis

In [19]:
print(np.sum(arr,axis=0),"\n") # sum along the rows
print(np.sum(arr,axis=1)) # sum along the columns 


[1.92845885 1.94830217 2.05660815 3.26560581 3.19421431] 

[2.82142971 2.90642156 2.4405474  2.10676081 2.11802982]


### Compute The Min And Max Along A Specified Axis

In [23]:
print(np.min(arr,axis=0),"\n") # min along rows
print(np.max(arr,axis=1),"\n") # max along columns

print(arr) # here's the original array to check

[0.06331533 0.10403926 0.10333645 0.42492636 0.4188741 ] 

[0.84231371 0.92989077 0.72095692 0.75340938 0.89898174] 

[[0.84231371 0.41435028 0.5828768  0.43642238 0.54546653]
 [0.50586142 0.10403926 0.65801292 0.92989077 0.70861718]
 [0.06331533 0.44156137 0.59243903 0.72095692 0.62227475]
 [0.28879635 0.54234453 0.10333645 0.75340938 0.4188741 ]
 [0.22817204 0.44600673 0.11994295 0.42492636 0.89898174]]


In [24]:
print(np.max(arr))
print(np.min(arr))
# if the axis is not specified, it'd calculate the min\max of all elements

0.9298907709832938
0.06331533299286574


### Compute The Indices Of The Min And Max Along A Specified Axis

In [25]:
# along rows
print(np.argmin(arr,axis=0))
print(np.argmax(arr,axis=0),"\n")

# along columns
print(np.argmin(arr,axis=1))
print(np.argmax(arr,axis=1),"\n")

# if axis is not specified, return the indexof the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

# you can double-check from the original array above


[2 1 3 4 3]
[0 3 1 1 4] 

[1 1 0 2 2]
[0 3 3 3 4] 

10
8


### Compute Element-Wise Min And Max Of Two Arrays

In [26]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([0,3,7,1])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))

# compares every two corresponding elements and prints their max/min

[1 3 7 4]
[0 2 3 1]


### Split The Fractional And Integral Parts Of A Floating-Point Array

In [29]:
arr1 = np.random.rand(10)*10
print(arr1,"\n")
frc, intg = np.modf(arr1)
print('The fractinoal part:',frc,"\n")
print('The integer part:',intg,'\n')

[6.19522168 5.76220842 6.43056511 7.78450116 3.11337565 8.87928486
 0.69615825 6.88198489 3.28326354 4.83483465] 

The fractinoal part: [0.19522168 0.76220842 0.43056511 0.78450116 0.11337565 0.87928486
 0.69615825 0.88198489 0.28326354 0.83483465] 

The integer part: [6. 5. 6. 7. 3. 8. 0. 6. 3. 4.] 



### Compute The Mean

In [30]:
print(np.mean(arr)) # overall mean

0.4957275718234171


In [31]:
print(np.mean(arr,axis=0)) # mean along rows

[0.38569177 0.38966043 0.41132163 0.65312116 0.63884286]


In [32]:
print(np.mean(arr,axis=1)) # mean along columns

[0.56428594 0.58128431 0.48810948 0.42135216 0.42360596]


### Compute The Median

In [33]:
print(np.median(arr)) # overall
print(np.median(arr,axis=0)) # rows
print(np.median(arr,axis=1)) # columns

0.5058614241533751
[0.28879635 0.44156137 0.5828768  0.72095692 0.62227475]
[0.54546653 0.65801292 0.59243903 0.4188741  0.42492636]


### Compute The Percentile 

In [38]:
arr1 = np.random.rand(20)
print(arr1,"\n")

# 5th, 65th, 95th, and 99th percentiles
print(np.percentile(arr1,[5,65,95,99]))

[0.87018801 0.59356799 0.99522479 0.25806461 0.71338477 0.67319224
 0.49736329 0.22955838 0.34170989 0.89177574 0.68935888 0.25190539
 0.47030533 0.96346166 0.74809093 0.35569776 0.0951436  0.17481921
 0.96816609 0.39605336] 

[0.17083543 0.69776794 0.96951903 0.99008364]


### Compute Standard Deviation And Variance

In [39]:
print(np.std(arr)) # overall
print(np.std(arr,axis=0)) # rows
print(np.std(arr,axis=1),"\n") # columns

print(np.var(arr)) # overall
print(np.var(arr,axis=0)) # rows
print(np.var(arr,axis=1)) # columns



0.24283233445712024
[0.26872741 0.14924482 0.24610879 0.19508565 0.1611959 ]
[0.15285877 0.27461932 0.23052969 0.22073166 0.26716711] 

0.0589675426578947
[0.07221442 0.02227402 0.06056954 0.03805841 0.02598412]
[0.0233658  0.07541577 0.05314394 0.04872247 0.07137826]


### Compute The Covariance & Correlation

In [41]:
arr = np.random.rand(3,4)
print(arr,"\n")

print(np.cov(arr))

[[0.69468558 0.18799676 0.77959143 0.72182488]
 [0.31619625 0.73244651 0.54949188 0.17237661]
 [0.3577829  0.80544534 0.64462182 0.46263677]] 

[[ 0.07524773 -0.04836965 -0.03893801]
 [-0.04836965  0.06147849  0.04401895]
 [-0.03893801  0.04401895  0.03918109]]


In [42]:
print(np.corrcoef(arr[:,0],arr[:,1]))

[[ 1.         -0.97829248]
 [-0.97829248  1.        ]]


### Compute Cumulative Sum & Product

In [46]:
print(np.cumsum(arr,axis=0),"\n") # along COLUMNS
print(np.cumsum(arr,axis=1)) # along ROWS

[[0.69468558 0.18799676 0.77959143 0.72182488]
 [1.01088183 0.92044328 1.32908331 0.89420149]
 [1.36866473 1.72588862 1.97370513 1.35683826]] 

[[0.69468558 0.88268234 1.66227378 2.38409865]
 [0.31619625 1.04864276 1.59813464 1.77051125]
 [0.3577829  1.16322824 1.80785006 2.27048683]]


In [48]:
print(np.cumprod(arr,axis=0),'\n') # along COLUMNS
print(np.cumprod(arr,axis=1),'\n') # along ROWS

[[0.69468558 0.18799676 0.77959143 0.72182488]
 [0.21965697 0.13769757 0.42837916 0.12442572]
 [0.07858951 0.11090787 0.27614255 0.05756392]] 

[[0.69468558 0.13059864 0.10181358 0.07349158]
 [0.31619625 0.23159684 0.12726058 0.02193675]
 [0.3577829  0.28817457 0.18576361 0.08594108]] 



### Element-Wise Comparison

In [49]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
# returns arrays of bools
print(arr1==arr2)
print(arr1>3)

[False False  True False False]
[False False False  True  True]
