In [1]:
import numpy as np

### Set Seed

In [2]:
np.random.seed(123)

### Set Random State Which Is Independent From The Global Seed

In [3]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### Generate A Random Sample From Interval [0,1) In A Given Shape

In [5]:
print(np.random.rand())# prints a random scalar
print(np.random.rand(3))# prints a 1-D array 
print(np.random.rand(3,3)) # prints a 2-D array 

0.28613933495037946
[0.22685145 0.55131477 0.71946897]
[[0.42310646 0.9807642  0.68482974]
 [0.4809319  0.39211752 0.34317802]
 [0.72904971 0.43857224 0.0596779 ]]


### Generate A Sample From Standard Normal Distribution (mean = 0, stdv = 1)

In [6]:
print(np.random.randn(3,3))

[[ 1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609]
 [ 1.0040539   0.3861864   0.73736858]]


### Generate An Array Of Random Integers in A Given interval [low, high)

In [9]:
# np.random.randint(low,high,size, dtype)
print(np.random.randint(3,17,6,'int16'))

[ 9  4 16  8 14  9]


### Generate An Array Of Random Floating-Point Numbers In The Interval [0.0,1.0)

In [10]:
# using various methods that are similar to np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.37380143 0.23451288 0.98799529 0.76599595 0.77700444 0.02798196
 0.17390652 0.15408224 0.07708648 0.8898657 ]
[0.7503787  0.69340324 0.51176338 0.46426806 0.56843069 0.30254945
 0.49730879 0.68326291 0.91669867 0.10892895]
[0.49549179 0.23283593 0.43686066 0.75154299 0.48089213 0.79772841
 0.28270293 0.43341824 0.00975735 0.34079598]
[0.68927201 0.86936929 0.26780382 0.45674792 0.26828131 0.8370528
 0.27051466 0.53006201 0.17537266 0.31496645]


### Generate A Random Sample From A Given 1-D Array

In [14]:
# np.random.choice(iterable, size, replace = True)
print(np.random.choice(3,10,replace=True))
print(np.random.choice(3,10))
print(np.random.choice([1,2,3],10))

[1 1 0 1 1 0 2 1 2 0]
[1 0 2 0 0 2 0 2 1 0]
[1 1 1 1 1 2 1 1 1 3]


### Shuffle An Array 

In [15]:
arr = np.array(range(10))
print(arr)

np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[4 7 3 5 2 0 9 1 6 8]


### Generate A Permutation Of An Array 

In [18]:
# similar to np.random.shuffle(), but it returns a copy rather than changing in place
arr = np.array(range(10))
print('The initial array:', arr)
print('A permutation of the array is:', np.random.permutation(arr))

# error below 
# print('A permutation of the array is:', np.random.schuffle(arr))

The initial array: [0 1 2 3 4 5 6 7 8 9]
A permutation of the array is: [0 3 8 4 6 7 9 2 1 5]
