In [1]:
import numpy as np

In [12]:
arr = np.random.rand(5,5)
print(arr)

[[0.68182388 0.38110785 0.93071508 0.75525837 0.52644715]
 [0.8058887  0.70520526 0.29340577 0.74641346 0.59043551]
 [0.03954199 0.01038335 0.95584316 0.19832931 0.10391654]
 [0.64260538 0.94840289 0.17054195 0.78669623 0.7429172 ]
 [0.88343983 0.6474838  0.32537387 0.92374683 0.00207365]]


### Sort An Array Along A Specified Axis 

In [19]:
print(np.sort(arr,axis=0), "\n") # sorts along columns 

print(np.sort(arr,axis=1)) # sorts along rows 

[[0.03954199 0.01038335 0.17054195 0.19832931 0.00207365]
 [0.64260538 0.38110785 0.29340577 0.74641346 0.10391654]
 [0.68182388 0.6474838  0.32537387 0.75525837 0.52644715]
 [0.8058887  0.70520526 0.93071508 0.78669623 0.59043551]
 [0.88343983 0.94840289 0.95584316 0.92374683 0.7429172 ]] 

[[0.38110785 0.52644715 0.68182388 0.75525837 0.93071508]
 [0.29340577 0.59043551 0.70520526 0.74641346 0.8058887 ]
 [0.01038335 0.03954199 0.10391654 0.19832931 0.95584316]
 [0.17054195 0.64260538 0.7429172  0.78669623 0.94840289]
 [0.00207365 0.32537387 0.6474838  0.88343983 0.92374683]]


### Compute The Indices That Would Sort An Array Along A Specified Axis

In [20]:
arr = np.random.rand(5,5)
print(arr)

[[0.46335561 0.03958151 0.73251774 0.95665494 0.45176237]
 [0.50810076 0.46030195 0.9344686  0.50229301 0.61126673]
 [0.92821027 0.33499396 0.24368766 0.92987526 0.39153904]
 [0.87526406 0.54401876 0.11231518 0.0974946  0.29543217]
 [0.65113689 0.71617536 0.49959612 0.35604578 0.62972442]]


In [23]:
print(np.argsort(arr,axis=0),'\n') # along columns 
print(np.argsort(arr,axis=1),'\n') # along rows

# returns indices of a flattened array
print(np.argsort(arr,axis=None))

[[0 0 3 3 3]
 [1 2 2 4 2]
 [4 1 4 1 0]
 [3 3 0 2 1]
 [2 4 1 0 4]] 

[[1 4 0 2 3]
 [1 3 0 4 2]
 [2 1 4 0 3]
 [3 2 4 1 0]
 [3 2 4 0 1]] 

[ 1 18 17 12 19 11 23 14  4  6  0 22  8  5 16  9 24 20 21  2 15 10 13  7
  3]
