<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [1]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model 

In [2]:
df = pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_


180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [7]:
import pickle #.pickle extension 

In [8]:
with open('model_pickle','wb') as file: # write to a binary file 
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [11]:
with open('model_pickle','rb') as file:
    new_model = pickle.load(file)

In [12]:
new_model.coef_

array([135.78767123])

In [13]:
new_model.intercept_

180616.43835616432

In [14]:
new_model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [15]:
import joblib 

In [16]:
joblib.dump(model,'model_joblibb')

['model_joblibb']

In [17]:
# function to save our model 
def save_model(model, model_name):
    import joblib
    joblib.dump(model,model_name)

<h4 style='color:purple'>Load Saved Model</h4>

In [19]:
joblib_model = joblib.load('model_joblibb')

In [20]:
joblib_model.coef_

array([135.78767123])

In [21]:
joblib_model.intercept_

180616.43835616432

In [22]:
joblib_model.predict([[5000]])

array([859554.79452055])