In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,4)
print(arr)

[[0.36594049 0.54400294 0.55519529 0.73378505]
 [0.66332515 0.46629412 0.71471096 0.86307239]
 [0.72590829 0.40221267 0.60255686 0.54708443]]


### Transpose An Array 

In [4]:
print(arr.T)
print(np.transpose(arr))
print(arr.transpose())

[[0.36594049 0.66332515 0.72590829]
 [0.54400294 0.46629412 0.40221267]
 [0.55519529 0.71471096 0.60255686]
 [0.73378505 0.86307239 0.54708443]]
[[0.36594049 0.66332515 0.72590829]
 [0.54400294 0.46629412 0.40221267]
 [0.55519529 0.71471096 0.60255686]
 [0.73378505 0.86307239 0.54708443]]
[[0.36594049 0.66332515 0.72590829]
 [0.54400294 0.46629412 0.40221267]
 [0.55519529 0.71471096 0.60255686]
 [0.73378505 0.86307239 0.54708443]]


### Change The Shape Of An Array 

In [5]:
arr.reshape((2,6)) # returns a copy

array([[0.36594049, 0.54400294, 0.55519529, 0.73378505, 0.66332515,
        0.46629412],
       [0.71471096, 0.86307239, 0.72590829, 0.40221267, 0.60255686,
        0.54708443]])

### Flatten An Array 

In [6]:
arr.flatten() # returns a copy

array([0.36594049, 0.54400294, 0.55519529, 0.73378505, 0.66332515,
       0.46629412, 0.71471096, 0.86307239, 0.72590829, 0.40221267,
       0.60255686, 0.54708443])

### Append Elements To An Array 

In [8]:
arr = np.array([1,2,3])
arr1 = np.append(arr,4) # append a scalar 
arr2 = np.append(arr1,[5,6,7])
print(arr1)
print(arr2)

[1 2 3 4]
[1 2 3 4 5 6 7]


### Insert Elements Into An Array 

In [9]:
arr3 = np.insert(arr,0,10)
print(arr3)

[10  1  2  3]


In [10]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0,[1,2,3])
print(arr3)

[1 2 3 1 2 3]


### Delete Elements From An Array 

In [12]:
arr4 = np.delete(arr,0) # remove by index
print(arr4)

arr4 = np.delete(arr,[0,2]) # remove at multiple positoins 
print(arr4)

[2 3]
[2]


### Copy An Array 

In [13]:
arr = np.array([1,2,3])


In [ ]:
# indintical methods for deep copying:
arr1 = np.copy(arr)
arr1 = arr.copy()
arr1 = np.array(arr,copy=True)