# Creating an array from Iterable

For example:
*list 
*tuple
*range iterator

In [1]:
import numpy as np

In [3]:
mylist = [1,2,3,4]
arr = np.array(mylist)
print(arr)
print(type(arr))

l = [1,2,3,4]
print(l)
print(type(l))
print(arr.dtype)

# notice in the numpy array there are no commans separating the values

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>
int64


In [4]:
arr = np.array((1,2,3))
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


In [8]:
arr = np.array(range(2,11,2))
print(arr)
print(type(arr))
print(arr.dtype)

arr = arr.astype(np.int8)
print(arr.dtype)

[ 2  4  6  8 10]
<class 'numpy.ndarray'>
int64
int8


# Creating An Array With A Previously Specified Value

In [10]:
arr = np.array([[1,2,3] ,[4,5,6]], dtype = "i2") # 2D array # "i2" -> int16
print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int16


In [12]:
arr= np.arange(0,21,3)
print(arr)
print(type(arr))
print(arr.dtype)

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>
int64


In [14]:
arr , step_size = np.linspace(0,5,8, endpoint = False, retstep = True) # creating an array of 8 numbers from 0 to 5
print(arr)
print(arr.size)
print('The step size is:', step_size)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375]
8
The step size is: 0.625


In [18]:
arr = np.random.rand(3,4)
print(arr) # A 2D array of 3 row and 4 columns with random numbers from 0 to 1

[[0.55998767 0.98069211 0.86309944 0.59633781]
 [0.05278036 0.89321489 0.02239408 0.17055076]
 [0.92285963 0.55583731 0.04551124 0.36512127]]


In [20]:
zeros = np.zeros((3,4))
print(zeros) # Float by default

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
empty = np.zeros(5)
print(empty)
for i in range(5):
    empty[i] = input()
print(empty)

[0. 0. 0. 0. 0.]
1
2
3
4
5
[1. 2. 3. 4. 5.]


In [25]:
arr = np.array([[1,2], [3,4], [5,6]], dtype = np.complex64)
print(arr,"\n")

zeros = np.zeros_like(arr) # Creates an array of zeros with the same dimension and data type as arr
print(zeros)
print('Data Type:', zeros.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]] 

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Data Type: complex64


In [26]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
arr = [[1,2,3],[4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('The data type is:', ones.dtype)

[[1 1 1]
 [1 1 1]]
The data type is: int64


In [30]:
empty = np.empty((3,3)) # Takes 3 * 3 places in the meomry. The random numbers are garbage of the previously used locations
print(empty)
print(empty.dtype)

[[ 3.45126646e-31 -6.90253292e-31  1.72563323e-31]
 [-6.90253292e-31  1.50130091e-30 -4.65920972e-31]
 [ 1.72563323e-31 -4.65920972e-31  2.67473151e-31]]
float64


In [36]:
new_arr = np.array([[1,2,3], [4,5,6]], dtype = np.int64)
empty = np.empty_like(new_arr)
print(empty)
print('Data Type is:', empty.dtype)

???? why this output?

[[1 2 3]
 [4 5 6]]
Data Type is: int64


In [37]:
full = np.full((4,4), 6)
print(full)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [38]:
arr = np.array([[1,2],[3,4]], dtype = np.float64)
full = np.full_like(arr,5) # Creates 5-valued array with the same data type
print(full)
print('The data type is:', full.dtype)

[[5. 5.]
 [5. 5.]]
The data type is: float64
