<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

<h3 style="color:purple">Sample problem of predicting home price in monroe, new jersey (USA)</h3>

Below is the table containing home prices in monroe twp, NJ. Here price depends on **area (square feet), bed rooms and age of the home (in years)**. Given these prices we have to predict prices of new homes based on area, bed rooms and age.

<img src="homeprices.jpg" style='height:200px;width:350px'>

Given these home prices find out price of a home that has,

**3000 sqr ft area, 3 bedrooms, 40 year old**

**2500 sqr ft area, 4 bedrooms,  5 year old**

We will use regression with multiple variables here. Price can be calculated using following equation,

<img src="equation.jpg" >

Here area, bedrooms, and age are called independant variables or **features** whereas price is a dependant variable

In [4]:
import pandas as pd 
import numpy as np 
from sklearn.linear_model import LinearRegression 

In [19]:
data = pd.read_csv('homeprices.csv')
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

**Data Preprocessing: Fill NA values with median value of a column**

In [22]:
data.bedrooms.median()

4.0

In [23]:
data.bedrooms.fillna(data.bedrooms.median(), inplace=True)
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [24]:
x = data.drop('price', axis = 'columns')
y = data.price

In [25]:
x

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [26]:
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [27]:
model = LinearRegression()
# fit(x,y) >>> training 
model.fit(x,y)

LinearRegression()

y = mx + c
y = mx1 + m2x2 + m3x3 + c 

In [29]:
model.coef_ # 3 coeffs for 3 m's 

array([  112.06244194, 23388.88007794, -3231.71790863])

In [30]:
model.intercept_ # only one intercept (c in the above equation)

221323.00186540425

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [32]:
model.predict([[3000,3,40]])

array([498408.25158031])

In [34]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [33]:
model.predict([[3000,4,40]])

array([521797.13165825])

**Find price of home with 2500 sqr ft area, 4 bedrooms,  5 year old**

In [35]:
model.predict([[2500,4,5]])

array([578876.03748933])

In [36]:
model.predict([[5000, 4, 0]])

array([875190.73188783])

In [38]:
model.score(x,y) # accuracy 

0.9550196399325818